added detekt to iosApp

diff --git a/config/git-hooks/pre-push b/config/git-hooks/pre-push
--- a/config/git-hooks/pre-push
+++ b/config/git-hooks/pre-push
@@ -41,4 +41,14 @@ if [ $EXIT_CODE -ne 0 ]; then
   echo "***********************************************"
   exit $EXIT_CODE
 fi
+detekt > OUTPUT
+EXIT_CODE=$?
+if [ $EXIT_CODE -ne 0 ]; then
+  cat OUTPUT
+  rm OUTPUT
+  echo "***********************************************"
+  echo "                 Swiftlint failed                 "
+  echo "***********************************************"
+  exit $EXIT_CODE
+fi
 rm OUTPUT
